### ISSUE TITLE
Whatsapp beta-multi device feature tests

### ISSUE THREAD

**Issue by rsoorajs** [orkestral/venom#1116]
As per my tests,Im concluding these about whatsapp beta-multi device feature

1. Qr code token never stores,2 or 3 qr codes appearing. After scanning second or 3rd qr code phone is successfully get connecting.(Without multi device feature,it will conntect on the first scan)

2. Session didnt storing.

3. When we did everything we will get connetion succed message in the telegram channel

4. All messages sending from Whatsapp are recieving in to telegram. But not recieving any single message or media from telegram to Whatsapp.

These are the issue which i can identify.Please fix it

**Comment by rsoorajs** [comment]
I already mentioned this issue on telegram,kindly consider it

**Comment by JuanFelix88** [comment]
1. It seems that it is a resource yet to be optimized by the WhatsApp team, since the behavior happens when connecting the webpage
2. The session was not yet implemented for the beta sessions

Maybe you can help:

- Do not use the beta until it is stabilized
- We try to identify the new patterns implemented in this new beta version
- Check changes over time by dealing with a beta version

**Comment by orkestral** [comment]
The multi device is still in beta and the vast majority showing flaws, we will only release the version when it is functional by whatsapp
