### ISSUE TITLE
Session is not restored after restart

### ISSUE THREAD

**Issue by luiscuriel** [orkestral/venom#1633]
## Description
I run venom, scan QR, whatsapp launches correctly. Then I close whatsapp, launch venom again, and it asks for QR evey time

**Comment by jesusvalverde** [comment]
Same here, I do delete the token folder and after 3-4 or maybe more it stays..

**Comment by tomanotomano** [comment]
Hello, We have the same problem. 
Token is not being created, using Whatsupp Bussines or Not. QR is always asked

Nos pasa lo mismo, no se crea el token, siempre pide el QR para volverse a loguear. Usando Whats Bussines o no

**Comment by jesusvalverde** [comment]
also with multi device or not..

**Comment by jesusvalverde** [comment]
same as  ? https://github.com/orkestral/venom/issues/1631

**Comment by joaocib** [comment]
I was having this problem and resolved by using these createOptions:

  multidevice: true,
  folderNameToken: 'tokens', //folder name when saving tokens
  mkdirFolderToken: './', //folder directory tokens, just inside the venom folder, example:  { mkdirFolderToken: '/node_modules' }
  createPathFileToken: true, //creates a folder when inserting an object in the client's browser
  
Also, i'm using browserSessionToken = null. (not passing anything on this parameter, my client logs write it as 'null')

In my view it means that the folder itself is the unique token of the session, so it reads that folder every time and restore the specified client.
In case you guys are using multidevice: false, I recommend you to start migrating because there is information that it will be deprecated soon.

**Comment by jonalan7** [comment]
This problem may be due to the replacement of the project's original Args!
Putting new information in browserArgs
If you are using this option, use the addBrowserArgs option

![image](https://user-images.githubusercontent.com/67329824/165529977-acfff05c-bd90-4235-9edf-fa666717f8ec.png)

https://github.com/orkestral/venom#optional-create-parameters

**Comment by jonalan7** [comment]
On the multiple device, it no longer creates just a Json file, it creates a folder with several files!
Use in venom options:

`multidevice: true`

![image](https://user-images.githubusercontent.com/67329824/165984278-39535907-e786-4ee7-93fd-5742c6d0283c.png)

If the folders do not automatically create in your project, it must be a permission problem!
Review your project, as the token folders must be created, if this does not happen, the session will not be returned!
I tested it here and it worked perfectly!

If by a miracle your whatsapp does not have the multideevice version, just put it in the venom options:

`multidevice: false`

**Comment by vielhuber** [comment]
Yes, that's correct, but:

- I use the latest nightly:

`"venom-bot": "https://github.com/orkestral/venom/releases/download/nightly/venom-bot-nightly.tgz"`

`
multidevice: true,
headless: true
`

Creates a folder:
![image](https://user-images.githubusercontent.com/3183737/166065850-1c05d31a-7a3e-4252-ba59-e73c22968a98.png)
But every time I reconnect, QR code is shown again.

And if I set:

`
multidevice: true,
headless: false
`
the session is saved and restored, also the folder content is much bigger:
![image](https://user-images.githubusercontent.com/3183737/166065902-83d63830-4e81-4859-8f9b-3e41c2d753fd.png)

Any clues about that?

**Comment by Ramstin13** [comment]
> On the multiple device, it no longer creates just a Json file, it creates a folder with several files! Use in venom options:
> 
> `multidevice: true`
> 
> ![image](https://user-images.githubusercontent.com/67329824/165984278-39535907-e786-4ee7-93fd-5742c6d0283c.png)
> 
> If the folders do not automatically create in your project, it must be a permission problem! Review your project, as the token folders must be created, if this does not happen, the session will not be returned! I tested it here and it worked perfectly!
> 
> If by a miracle your whatsapp does not have the multideevice version, just put it in the venom options:
> 
> `multidevice: false`

hey jonalan,

how can i check if there is a permission problem? 

i am using multidevice: true
i don't see any tokens folder.

**Comment by matbks** [comment]
My problem is similar, after restarting my session connects but wont work.

**Comment by FelipeVeiga** [comment]
same here
