### ISSUE TITLE
"Checking is logged" step never ends when creating a session with the same name for the second time

### ISSUE THREAD

**Issue by LuanEdCosta** [orkestral/venom#1672]
## Description

After creating a session, I waited for the QRCode to expire and the page to close. After that I tried to create another session with the same session name, but some error occurred behind the scenes and I was stuck in "Checking is logged".

I am creating a RESTful API with venom-bot. There is an endpoint in my application to create a session.

## Environment

- **Venom version(s):** 4.0.11
- **Browser:** Chrome 101
- **OS:** Windows 10
- **Node version:** 16.13.0

## Steps to Reproduce

1. Create a session with a name/identifier
2. Wait for the QRCode to expire and the page to close
3. Try to create the session with the same name/identifier again
4. You will be stuck at the "Checking is logged" step

Obs 1: I believe that the problem is related to the tokens folder, because venom-bot creates a folder with the name of the session inside of it. Maybe venom tries to update or create some files and fails because these files are being used by another process (my API in this case).

OBS 2: I'm facing this error with a RESTful API. If I restart the API, the bug does not happen. 

## Log Output

No.

## Additional context / Screenshot

![image](https://user-images.githubusercontent.com/36794274/168943941-dd1bef15-67fc-4616-a9e4-a425d991b79a.png)

**Comment by chrisk8er** [comment]
Same here...

**Comment by LuanEdCosta** [comment]
I solved my problem using a different session name each time. I appended `Date.now()` to the session name.

**Comment by claudecir** [comment]
what was the solution to this problem? I'm also facing the same here, I saw that they closed but no new release was generated

**Comment by LuanEdCosta** [comment]
The solution for me was to use a different session name to create each session.

```javascript
venom.create({
  session: `session_${Date.now()}`
})
```

**Comment by joaocib** [comment]
My solution:

When you create a session, you receive that Whatsapp : Client.
This client has a propertie called: Page
The propertie has a method called: page.browser(); -- returns the browser with the PID for chromiun.exe/chrome.exe tab
So if you declare like this:
`let browser;`
`browser = Whatsappclient.page.browser();`
`browser.close()`

You browser now is closed, and if you are saving correctly the userdatadir for this browser, you won't need rename the session, because next time it will open that same tab. You won't need scan QRcode again either.

**Comment by joaocib** [comment]
> 

Also, this issue is directly caused by headless option... if you use
`headless: false`
you will see that he directly kill the browser instead. Is very strange.
My advice is to operate headless, but if you are facing issues, you can use this options to you favor by seeing visually what is happening to the browser. Just keep in mind that this option may affect some client based functions.

**Comment by xbral** [comment]
![image](https://github.com/orkestral/venom/assets/6523757/89d860be-bcf7-4b29-816c-763e0219795d)
I found that sometimes he gets the "Checking is Logged" message in a loop because he's accessing the wrong page. Go to the Facebook page above.
