### ISSUE TITLE
abandoned project?

### ISSUE THREAD

**Issue by antoniovalenzuela** [orkestral/venom#1918]
last release a month ago

**Comment by DevSamuelOliveira** [comment]
In fact, I hope the community continues to maintain it. I honestly don't know what direction my life would have taken if it wasn't for this incredible tool. Sustained me during the pandemic

**Comment by acognigni-evotecnia** [comment]
Hi. I do not work for venom but Ivéasked this question a few times. no. venom is not dead. they just take a really long time to release things (even a single commit), and then release a single version that fixes all open issues. 
venom was bought by another company and it's apparently not profitable enough to have a permanent dev / support team. so they do it every once in a a while. however keep in contact with the community on telegram and checkout pull requests every once in a while. a few times when there are serious issues the community made pull requests that you can download and use instead of the latest release

**Comment by acognigni-evotecnia** [comment]
BTW. last time i asked if the project was dead, it had been 3 months since the last release and like 2 months since the las commit. i got in touch with the owner on telegram to ask this

**Comment by orkestral** [comment]
Sorry for the delay, we will resume updates weekly, the project is not dead. we're back.
