### ISSUE TITLE
 Error on sendImageAsStickerGif

### ISSUE THREAD

**Issue by gifuzzz** [orkestral/venom#482]
## Description

I get this error whenever I try to send a gif as an animated sticker. sendImageAsSticker works properly, but sendImageAsStickerGif, doesn't. It may seem strange or impossible, but up to one hour and half hours ago, it used to work properly, too.

## Environment

- **Venom version(s):** 2.2.3
- **OS:** macOS Big Sur 11.0.1
- **Node version:** 12.18.3

## Log Output

(node:70526) UnhandledPromiseRejectionWarning: Error: Evaluation failed: n
    at ExecutionContext._evaluateInternal (/Users/luigi/Documents/Programming/Node_js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/Users/luigi/Documents/Programming/Node_js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
(node:70526) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:70526) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## Your Code
```

client.sendImageAsStickerGif(message.from, 'out.gif')
.then((result) => {
    console.log(result)
    fs.unlinkSync('out.gif')
    fs.unlinkSync('video.mp4')
})
.catch((err) => console.log('Error: ', err))

```

**Comment by gifuzzz** [comment]
well, I didn't change anything and now if work again...

**Comment by gifuzzz** [comment]
here it is again

**Comment by edgardmessias** [comment]
@gifuzzz , could you please attach the gif?

**Comment by gifuzzz** [comment]
> @gifuzzz , could you please attach the gif?

![out](https://user-images.githubusercontent.com/62186853/103582694-aa315c80-4ede-11eb-9e42-17d9bfe9e6c0.gif)

**Comment by Fredwuz** [comment]
Yeah this problem occurs if the gif after the conversion to webp is larger than 1MB I also had an open issue about this 
#251 
They tried to fix it by limiting the gif input size to 512x512 I but this won't solve the problem because the problem isn't the dimensions of the image its the file size
Note the file Size decreases after the conversion into webp always differently so it also would help just to set the input gif size to 1mb in the other issue there is a table with some information when testing with stickers
Here is the Table

| Picture | Gif Original File Size | File Size after Converting by Venom | File Size after Sending | Gif/Sent ratio | Converted/Sent ratio | Gif/Converted ratio |
|---------|------------------------|-------------------------------------|-------------------------|----------------|----------------------|---------------------|
| 1       | 346687                 | 258708                              | 194030                  | 0.55966909633  | 0.74999613463        | 0.7462293077        |
| 2       | 83204                  | 49096                               | 36820                   | 0.44252680159  | 0.74995926348        | 0.5900677852        |
| 3       | 414018                 | 313160                              | 234870                  | 0.56729417561  | 0.75                 | 0.75639223415       |
| 4       | 262505                 | 141048                              | 105784                  | 0.40297899087  | 0.74998582043        | 0.5373154797        |
| 5       | 1404020                | 1326688                             | 995016                  | 0.70869075939  | 0.75                 | 0.94492101252       |

**Comment by gifuzzz** [comment]
> Yeah this problem occurs if the gif after the conversion to webp is larger than 1MB I also had an open issue about this
> #251
> They tried to fix it by limiting the gif input size to 512x512 I but this won't solve the problem because the problem isn't the dimensions of the image its the file size
> Note the file Size decreases after the conversion into webp always differently so it also would help just to set the input gif size to 1mb in the other issue there is a table with some information when testing with stickers
> Here is the Table
> 
> Picture	Gif Original File Size	File Size after Converting by Venom	File Size after Sending	Gif/Sent ratio	Converted/Sent ratio	Gif/Converted ratio
> 1	346687	258708	194030	0.55966909633	0.74999613463	0.7462293077
> 2	83204	49096	36820	0.44252680159	0.74995926348	0.5900677852
> 3	414018	313160	234870	0.56729417561	0.75	0.75639223415
> 4	262505	141048	105784	0.40297899087	0.74998582043	0.5373154797
> 5	1404020	1326688	995016	0.70869075939	0.75	0.94492101252

Thank you. So the only thing I could try is to compress the gif?

**Comment by Fredwuz** [comment]
Yeah probably you could also try to make it smaller when degreasing in dimension for example to 256x256 if the original dimensions where larger

**Comment by gifuzzz** [comment]
Okay, thank you!

**Comment by matheust3** [comment]
I'm having the same problem. Is there anything new that solves the problem?

**Comment by gifuzzz** [comment]
> I'm having the same problem. Is there anything new that solves the problem?

When I get this error I just reduce sticker size, like @Fredwuz said.
