### ISSUE TITLE
How i can use nodemon with venom?

### ISSUE THREAD

**Issue by NiedsonEmanoel** [orkestral/venom#722]
Whenever I try to use, the node is in an eternal loop.

**Comment by Dhyeythumar** [comment]
This happens because for every run `WAToken1 `and `WAToken2 `changes, thus JSON file changes and nodemon monitors the JSON files also. You have to create `nodemon.json` or add nodemon configs to `package.json` file to ignore the changes made in tokens folder.

Check out this for more information on ignoring files - https://github.com/remy/nodemon#config-files

I am using this in my `package.json` file:
```
"nodemonConfig": {
      "ignore": [
          "tokens/*"
      ],
      "delay": "2500"
},
```

**Comment by NiedsonEmanoel** [comment]
Thanks, issue solved.
