### ISSUE TITLE
checkNumberStatus fails with groups

### ISSUE THREAD

**Issue by AndersonVale** [orkestral/venom#738]
## Description

src/lib/wapi/functions/check-send-exist.js
 ln: 141  let ck = await window.WAPI.checkNumberStatus(chatId);

returns : 'The number does not exist'

## Steps to Reproduce

try send a text message to a group using the pattern : 0000000-00000@g.us

**Comment by jonalan7** [comment]
**A group is not a contact number! There is no way to check if it exists! I could do a function for this, but only if the group is on your chat list**

**Comment by sergiooak** [comment]
### Reopening with more information.

@jonalan7 information, It's not right. Yes you can use `checkNumberStatus` to check if a group ID like "0000000-00000@g.us" is valid, It will return if your group exists and is able to receive a message or not.

In fact, this function is called inside every single request like `client.sendText` per example. ([source](https://github.com/orkestral/venom/blob/master/src/lib/wapi/functions/send-message.js))

---

### New information:
I was using Venom a long time ago (before 3.0), and I had made a super simple script, to response every message the bot receives, it was working just fine
```js
( ... )
client.onMessage(async (message) => {
    try {      
      await client.sendText(
        message.from,
        "test"
      );
    } catch (error) {
      console.error(error);
    }
}
( ... )
```

Yesterday I tested the same script whiteout update it, when a User sends the bot a message, it responds...
But when a group sends a message, the bot fails to respond, with the message 'The number does not exist'.
This is how I found this closed issue...

Doing a research, I've found that `client.checkNumberStatus()` returned the exactly same error when checking a group id, and found it's a wrapper to `window.WAPI.checkNumberStatus()` that is called on every single "send" requests.

Somehow it now fails when it checks if the ID exist and throw an error when we use it.

### Temp fix:
I have directly changed the `node_modules/venom-bot/dist/lib/wapi/wapi.js` (compiled file), forcing a status 200 to bypass the error, and now I was able to send message to groups again.
```diff
( ... )
window.WAPI.checkNumberStatus = async function(e) {
            try {
                const t = await window.Store.WapQuery.queryExist(e);
                if (404 === t.status) throw 404;
                if (void 0 === t.jid) throw 404;
                const n = window.WAPI._serializeNumberStatusObj(t);
                return 200 == n.status && (n.numberExists = !0), n
            } catch (t) {
                return window.WAPI._serializeNumberStatusObj({
+                   status: 200,
                    jid: new window.Store.WidFactory.createWid(e)
                })
            }
        }
( ... )
```

### More information
- It's happening in every single venom version, so It is probably caused by some change on WhatsApp Web's source code
- Before compile, it is located on: `src/lib/wapi/functions/check-send-exist.js`
- My client is in pt/BR
- I'm not using WhatsApp beta
