### ISSUE TITLE
[Request] venom paid implementation 

### ISSUE THREAD

**Issue by a7medo778** [orkestral/venom#75]
hey guys,
so i been looking for some help integrating venom into a project i am doing (basically a whatsapp channel), is the core team doing paid implementation services? those can be turned into monthly licenses to keep the project going

i can really use the help, and sorry if this was the wrong place to place it

**Comment by joaosouz4** [comment]
hey, what kind of implementation do you need? maybe I can help you.

**Comment by robsonmessias** [comment]
Hello. I like to study and research things about technology. I was seeing an article on the internet that took me to your github.
I don't really understand github and I copied your project.
I don't need any implementation at the moment.
Did you create the venom?
I tested it and liked the result.
Venom is an excellent tool.

Enviado do Email para Windows 10

De: João Victor Souza
Enviado:quinta-feira, 23 de julho de 2020 11:12
Para: orkestral/venom
Cc:Subscribed
Assunto: Re: [orkestral/venom] [Request] venom paid implementation (#75)

hey, what kind of implementation do you need? maybe I can help you.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Este email foi escaneado pelo Avast antivírus.
https://www.avast.com/antivirus

**Comment by joaosouz4** [comment]
It was not me who created Venom, it came out based on another project called Sulla, which was discontinued, soon creates Venom and we are maintaining it with the help of several collaborators. And I am just one of them. Anything can come to me so I can help you. It is very good for me to have new contacts.

REPO: [https://github.com/orkestral/venom/issues/75](url)

**Comment by joaosouz4** [comment]
@a7medo778  can i close this ?

**Comment by a7medo778** [comment]
> hey, what kind of implementation do you need? maybe I can help you.

hey mate, i am looking to integrate it as a channel into a omni channel messanger project
it has to be scalable
