### ISSUE TITLE
npm install venom-bot não está instalando a versão mais atual

### ISSUE THREAD

**Issue by billbarsch** [orkestral/venom#77]
olá,
primeiramente parabens pelo trabalho incrivel

estou executando o comando de instalação mas ele não traz os arquivos que estão atualizados aqui no github
em vez disso ele instala uma versão antiga que tem problemas de mimetypes etc, notei que os arquivos do github tem muitas melhorias.

porque o npm não está pegando a master mais atual?

**Comment by joaosouz4** [comment]
Estamos preparando uma versão melhor e ainda não atualizamos no npm.

**Comment by robsonmessias** [comment]
Você é brasileiro tbm?! Agora que parei pra ler seu nome.
Eu gastando google translator pra te escrever em inglês..kkk
Então, você que criou o Venom?
É uma excelente api.
Eu não conheço o GitHub direito, mas acabei copiando seu projeto.
Tem algum problema?


Enviado do Email para Windows 10

De: João Victor Souza
Enviado:quinta-feira, 23 de julho de 2020 11:12
Para: orkestral/venom
Cc:Subscribed
Assunto: Re: [orkestral/venom] npm install venom-bot não está instalando a versão mais atual (#77)

Estamos preparando uma versão melhor e ainda não atualizamos no npm.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Este email foi escaneado pelo Avast antivírus.
https://www.avast.com/antivirus

**Comment by joaosouz4** [comment]
@robsonmessias 
It was not me who created Venom, it came out based on another project called Sulla, which was discontinued, soon creates Venom and we are maintaining it with the help of several collaborators. And I am just one of them. Anything can come to me so I can help you. It is very good for me to have new contacts.

REPO: https://github.com/orkestral/venom/issues/75

**Comment by orkestral** [comment]
Resolvido versão atualizada no npm 1.1.0

**Comment by billbarsch** [comment]
https://github.com/billbarsch/myzap

estou escrevendo essa api express usando o venom
varios amigos estão usando, o projeto tende a crescer muito e ser muito usado, 
contem com a gente aqui no que for preciso ;-)
